project:
  key: MAIL
  plan:
    key: MLAND
    name: mailcheck.co fb console https://console.firebase.google.com/project/mailcheck-landing/overview
stages:
- jobs:
  - scripts:
    - '[ "$bamboo_repository_git_branch" = "master" ] && docker build --force-rm=true --build-arg firebasekey=$bamboo_firebasekey --tag=registry.nodeart.io/mailcheck/land:latest .'
    - '[ "$bamboo_repository_git_branch" = "master" ] && docker rmi registry.nodeart.io/mailcheck/land:latest'
